name: C/C++ CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2022
  
    steps: 
    - name: Checkout SevenKewp
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout plugins
      uses: actions/checkout@v4
      with:
        repository: wootguy/SevenKewp_plugins
        path: ./plugins/SevenKewp_plugins

    - name: Build server and plugins
      run: |
        mkdir build && cd build
        cmake ..  -A win32 -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        cmake --build . --config Release

    - name: Build client
      run: |
        cd build
        cmake ..  -A win32 -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        cmake --build . --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-windows
        path: build/output/

  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout SevenKewp
      uses: actions/checkout@v4
      with:
        submodules: 'false'

    - name: Checkout plugins
      uses: actions/checkout@v4
      with:
        repository: wootguy/SevenKewp_plugins
        path: ./plugins/SevenKewp_plugins
    
    - name: Download and install dependencies
      run: |
        sudo apt install gcc-multilib g++-multilib libc6-dev-i386
        mkdir build

    - name: Build server and plugins
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_CLIENT=OFF -DBUILD_SERVER=ON -DBUILD_PLUGINS=ON
        make

    - name: Build client
      run: |
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_PLUGINS=OFF
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sevenkewp-linux
        path: build/output/
